python /home/tyzheng/SISR/distribution_inspect.py \
  --model_name DPSR \
  --ckpt /home/tyzheng/SISR/checkpoints/DPSR_x2_0325_1727.pth \
  --scale 2 \
  --channel_nums 32 \
  --num_blocks 5 \
  --w_bits 4 \
  --a_bits 4 \
  --val_dir /home/tyzheng/Datasets_pt/val/Set5 \
  --max_batches 20 \
  --max_layer_plots 0 \
  --save_dir /home/tyzheng/SISR/analysis/distribution_dpsr_layers