conda run -n SISR python final_test.py \
  --dpsr-checkpoint "./checkpoints/DPSR_x4_0815_1611.pth" \
  --fsrcnn-checkpoint "./checkpoints/FSRCNN_x4_0806_1601.pth" \
  --scale 4 \
  --channel_nums 32 \
  --subnet_channels 16 \
  --num_blocks 5 \
  --in_channels 3 \
  --arm_threshold 20 \
  --arm_subnet_threshold 5 \
  --device cuda
